stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: atriarch-simc-simulation:latest
      pushRemote: true
      registry: docker.atriarch.systems
    env:
      PLUGIN_MTU: "1400"
timeout: 50
branch:
  include:
  - shadowlands
notification:
  recipients:
  - recipient: dan@mail.atriarch.systems
    notifier: c-56lvs:n-45qs9
  condition:
  - Failed
